<?php
require __DIR__ . '/../inc/header.inc';

?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/../inc/breadcrumbs.inc'; ?>
        </div>
    </div>

    <div>
        <h3>Got a query?</h3>
        <p>Please use the contact form to the left to contact us with any queries or problems you may be experiencing. If you have any problems with the form, you can email us at <a href="mailto: info@bencerewards.co.uk">info@bencerewards.co.uk</a>.</p>
        <h3>Prefer to call?</h3>
        <p>If you prefer to call us, you are welcome to phone us on <strong>0117 9527740</strong>.</p>
    </div>

</main>

<?php require __DIR__ . '/../inc/footer.inc'; ?>
