<?php require __DIR__ . '/inc/header.inc'; ?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/inc/breadcrumbs.inc'; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h2>Welcome, Dave!</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h3>Account Details <a href="/account/update"><span class="glyphicon glyphicon-pencil"></span></a></h3>
        </div>
        <div class="col-xs-12">
            <div class="col-md-2 align-right">
                <p>Full Name: </p>
                <p>Company Name:</p>
                <p>Account Number:</p>
                <p>Phone Number: </p>
                <p>Email address: </p>
            </div>
            <div class="col-md-4">
                <p>David Fakhir</p>
                <p>Finders Keepers UK</p>
                <p>FK123</p>
                <p>07895971222</p>
                <p>dave@finderskeepersuk.com</p>
            </div>
            <div class="col-md-2 align-right">
                <p>Address:</p>
                <p>Postcode:</p>
                <p>Region:</p>
            </div>
            <div class="col-md-4">
                <p></p>
                <p></p>
                <p></p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h4>Admin Tools</h4>
        </div>
        <div class="col-md-4">
            <ul>
                <li><a href="#">Notification Centre</a></li>
                <li><a href="#">View User List</a></li>
                <li><a href="#">Import Data</a></li>
            </ul>

        </div>
        <div class="col-md-8">
            No users have been registered for 2016 yet, please check back later.
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h5>Stats</h5>
        </div>
        <div class="col-md-6">
            <?php echo $data['stats']['circles']; ?>
        </div>
        <div class="col-md-6">
            <?php echo $data['stats']['info']; ?>
        </div>
    </div>
</main>

<?php require __DIR__ . '/inc/footer.inc'; ?>
