<?php
require __DIR__ . '/inc/header.inc';

$user = $_SESSION;
?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/inc/breadcrumbs.inc'; ?>
        </div>
    </div>
    <div class="col-xs-12">
        <h2>Welcome, <?= $user['name'] ?>!</h2>
    </div>
    <div class="col-xs-12">
        <h3>Account Details <a href="#"><span class="glyphicon glyphicon-pencil"></span></a></h3>
    </div>


    <div class="col-xs-12">
        <div class="col-md-6">
            <div class="col-md-4 align-right">
                <p>Full Name: </p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['name'] ?: '--'); ?></p>
            </div>
            <div class="col-md-4 align-right">
                <p>Company Name:</p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['company'] ?: '--'); ?></p>
            </div>
            <div class="col-md-4 align-right">
                <p>Account Number:</p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['accNo'] ?: '--'); ?></p>
            </div>
            <div class="col-md-4 align-right">
                <p>Phone Number: </p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['phone'] ?: '--'); ?></p>
            </div>
            <div class="col-md-4 align-right">
                <p>Mobile Number: </p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['mobile'] ?: '--'); ?></p>
            </div>
            <div class="col-md-4 align-right">
                <p>Email address: </p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['email'] ?: '--'); ?></p>
            </div>
        </div>

        <div class="col-md-6">
            <div class="col-md-4 align-right">
                <p>Region:</p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['r_name'] ?: '--'); ?></p>
            </div>
            <div class="col-md-4 align-right">
                <p>Address:</p>
            </div>
            <div class="col-md-8">
                <p><?php echo($user['address1'] ?: '--'); ?></p>
                <?php echo '<p>' . $user['address2'] . '</p>'; ?>
                <?php echo '<p>' . $user['address3'] . '</p>'; ?>
                <?php echo '<p>' . $user['address4'] . '</p>'; ?>
                <p><?php echo($user['postcode'] ?: '--'); ?></p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-6">
            <h4>Admin Tools</h4>
            <div class="col-md-12">
                <ul>
                    <li><a href="account/notifications">Notification Centre</a></li>
                    <li><a href="#">View User List</a></li>
                    <li><a href="account/import">Import Data</a></li>
                </ul>

            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <table class="table">
                <thead>
                <tr>
                    <th>Users</th>
                </tr>
                </thead>
                <?php
                if (!empty($data['users'])) {
                    foreach ($data['users'] as $user) {
                        echo "<tr><td><a href='?uid=" . $user['id'] . "'>" . $user['name'] . "</a></td></tr>";
                    }
                } ?>
            </table>
            <?php
            if (empty($data['users'])) {
                // @todo: this needs to show for access > 1 only
                echo '<p>No users have been registered for 2016 yet, please check back later.</p>';
            }
            ?>

        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h5>Stats</h5>
        </div>
        <div class="col-md-6">
            <?php echo $data['stats']['circles']; ?>
        </div>
        <div class="col-md-6">
            <?php echo $data['stats']['info']; ?>
        </div>
    </div>
</main>

<?php require __DIR__ . '/inc/footer.inc'; ?>
