<?php require __DIR__ . '/inc/header.inc'; ?>

<main class="container">
    <div class="row no-pad">
        <div class="col-xs-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="http://i.imgur.com/iTjYrFT.jpg?1" alt="...">
                        <div class="carousel-caption">
                            ...
                        </div>
                    </div>
                    <div class="item">
                        <img src="http://i.imgur.com/iTjYrFT.jpg?1" alt="...">
                        <div class="carousel-caption">
                            ...
                        </div>
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row no-pad">
        <?php
        foreach($data['promos'] as $promo) { ?>
            <div class="col-md-4">
                <div class="feature-box" style="background-image: url('<?php echo $promo['thumb']; ?>');">
                    <h3><?php echo $promo['title']; ?></h3>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="row no-pad">
        <div class="col-xs-12">
            <div class="slightly-centred-div ipsum">
                Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.
            </div>
        </div>
    </div>
</main>

<?php require __DIR__ . '/inc/footer.inc'; ?>

