<?php
require __DIR__ . '/inc/notifications.inc';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
    <title>Travis Perkins Reward Scheme 2014 | Powered by Finders Keepers Ltd</title>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Finders Keepers Ltd" />
    <link rel="stylesheet" type="text/css" href="/css/style.css" title="1024px style" media="screen,projection" />
    <script src="/js/jquery.min.js" type="text/javascript"></script>

    <script>
        $(function() {
            $('select#regions').change(function() {
                var region = $(this).val();
                if (region == "All") {
                    $('#users tbody tr').show();
                } else {
                    $('#users tbody tr').hide();
                    $('#users tbody td[data-region="' + region + '"]').parent('tr').show();
                }
            });

            $('select#access').change(function() {
                var access = $(this).val();
                if (access == "All") {
                    $('#users tbody tr').show();
                } else {
                    $('#users tbody tr').hide();
                    $('#users tbody tr[data-access="' + access + '"]').show();
                }
            });

            $('#users tbody tr').click(function() {
                $(this).toggleClass('active');
                $(this).find('input').prop('checked', $(this).hasClass('active'));
            });

            $('#users .all-users').change(function() {
                if ($(this).is(':checked')) {
                    $('#users tbody tr:visible').addClass('active').find('input').prop('checked', true);
                } else {
                    $('#users tbody tr:visible').removeClass('active').find('input').prop('checked', false);
                }
            });

        });
    </script>

    <style>
        #users tbody tr {
            cursor: pointer;
        }

        #users tbody tr.active {
            background: #cccccc;
        }
    </style>

</head>

<body>
<div id="wrap">

    <div id="header">
        <p id="toplinks" style=""><span style="color: #FFF;"><a href="/account/">Account</a> | <a href="/account/logout.php">Logout</a></span></p>
        <h1>&nbsp;</h1>
        <p id="slogan">&nbsp;</p>
    </div>

    <div>

        <form action="/account/notifications/email.php" method="POST">
            <input type="submit" value="Select Users" />
            <table width="100%" id="users">
                <thead>
                <tr>
                    <th>Select All</th>
                    <th></th>
                    <th></th>
                    <th><label>Access Levels:</label>
                        <select id="access">
                            <option value="All">All</option>
                            <option value="1">Standard Users</option>
                            <option value="2">Branch Managers</option>
                            <option value="3">Regional Managers</option>
                            <option value="4">Sales Director</option>
                            <option value="5">Admins</option>
                        </select>
                    </th>
                    <th>
                        <select id="regions">
                            <option>All</option>
                            <?php foreach($regions as $region) { ?>
                                <option value="<?php echo $region['r_id']; ?>"><?php echo $region['r_name']; ?></option>
                            <?php } ?>
                        </select>
                    </th>
                </tr>
                <tr>
                    <td><input type="checkbox" class="all-users" /></td>
                    <th>Account No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Region</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($users as $user) {
                    if (empty($user['access'])) $user['access'] = 1;
                    ?>
                    <tr data-access="<?php echo $user['access']; ?>">
                        <td><input type="checkbox" name="user['<?php echo $user['id']; ?>']" value="<?php echo $user['id']; ?>" /></td>
                        <td><?php echo $user['accNo'] ?></td>
                        <td><span title="<?php echo $user['company'] ?>"><?php echo $user['name'] ?></span></td>
                        <td><?php echo $user['email']; ?></td>
                        <td data-region="<?php echo $user['r_id']; ?>"><?php echo $user['r_name']; ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <input type="submit" value="Select Users" />
        </form>
    </div>

    <div id="footer">
        <p><a href="/contact">Contact us | </a><a href="/terms">Terms and Conditions</a> | <a href="/privacy">Privacy policy </a>| <a href="/access">Access Statement </a>|<a href="/conditions"> Conditions of use </a>| <a href="#header">Back to top</a> <br />
            &copy; 2014 Finders Keepers Ltd | Design by <a href="http://www.finderskeepersuk.com/" target="_new">Finders Keepers Sports and Marketing Ltd</a><br />
        </p>
        <div><strong>Registered office:</strong> Lodge Way House,&nbsp;&nbsp;Lodge Way,&nbsp;&nbsp;Harlestone Road,&nbsp;&nbsp;Northampton&nbsp;&nbsp;NN5 7UG</div>
        <p>Registered in England No: 00824821 VAT registration number: 408556737</p>
        <p></p>
        <p>&nbsp; </p>
    </div>

</div>
</body>
</html>