<footer>
    <div class="container">
        <div class="col-xs-12">
            <nav class="slightly-centred-div">
                <a href="/contact">Contact Us</a>| <a href="/terms">Terms and Conditions</a> |
                <a href="/privacy">Privacy Policy</a> | <a href="/access">Access Statement</a> |
                <a href="/conditions">Conditions of use</a> | <a href="#">Back to top</a>
            </nav>
            <div class="slightly-centred-div metadata">
                <div>&copy; 2014 Finders Keepers Ltd | Design by <a href="http://www.finderskeepersuk.com">Finders Keepers Sports and Marketing Ltd</a></div>
                <div>Registered office: Lodge Way House, Lodge Way, Harlestone Road, Northampton, NN5 7UG</div>
                <div>Registered in England No: 00824821 VAT registration number: 408556737</div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>